# Generated by Django 3.1.2 on 2020-11-22 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('switchinfo', '0003_switchgroup'),
        ('pimanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='interface',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='switchinfo.interface', verbose_name='Port'),
        ),
    ]
