# Generated by Django 3.1.5 on 2021-03-03 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('switchinfo', '0003_switchgroup'),
        ('pimanager', '0002_device_interface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='interface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='switchinfo.interface', verbose_name='Port'),
        ),
    ]
